### ISSUE TITLE
Configuring iD editor to use the server

### ISSUE THREAD

**Issue by guyarad** [TimSC/pycrocosm#13]
Thanks for your project! 
Overall setup was easy (although I found that it's not working with PostgreSQL 10.3 with given instructions).
Now I'm wondering how can I configure a local installation of iD editor to use the server. I know that's a different project, but maybe you had some experience with it.

Thanks!

**Comment by guyarad** [comment]
I have managed to configure the editor to point to the new server. I changed the URL (including the consumer key and secret) in `index.html`. There are still *many* references to openstreetmap.org in the editor's code. But the server seems to be being hit. However, there are lots of exceptions - was this server ever tested in real-life?

**Comment by TimSC** [comment]
I've been testing the server over the last few months but only with josm. It seems to be fairly stable but some API calls have not been implemented. I'd be interested in seeing what types of errors you get or how I can reproduce. Is it just a case of running the iD editor and pointing it at the server?

**Comment by guyarad** [comment]
I followed your installation instructions and downloaded only the UK area from the links you provided (BTW, couldn't build `pgmap` on MacOS - failed something with SWIG which I didn't put an effort debugging yet). Then I installed the iD editor using the instructions on their website. It was quite a breeze (on MacOS). The JavaScript code contained numerous references to `openstreetmap.org` so I didn't change them all, but only the one reference on `index.html`.

Here are some examples of errors: 

```
[18/Mar/2018 14:32:23] "GET /api/api/0.6/map?bbox=34.793701171875504,32.07326555104209,34.799194335938004,32.07792017378799 HTTP/1.1" 200 10
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/text.py", line 329, in compress_sequence
    for item in sequence:
  File "/var/pycrocosm/querymap/views.py", line 54, in next
    ret = self.mapQuery.Continue()
  File "/usr/local/lib/python2.7/dist-packages/pgmap.py", line 2306, in Continue
    return _pgmap.PgMapQuery_Continue(self)
RuntimeError: Standard runtime exception: Transaction has been deleted
[18/Mar/2018 14:32:23] "GET /api/api/0.6/map?bbox=34.793701171875504,32.07326555104209,34.799194335938004,32.07792017378799 HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41810)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------```

**Comment by guyarad** [comment]
Quick update - I have tested your server with JOSM and indeed seems to be working! Only managed to use the semi-automatic authentication without too much investigation.

**Comment by TimSC** [comment]
I've started trying to use the iD editor. Did you have to work around the error "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:8000/api/capabilities. (Reason: CORS header 'Access-Control-Allow-Origin' missing)."? I think I need to enable it on the API server but I just wondered what you did.

JOSM doesn't display tiles in the background by default but they can be enabled in the imagery drop down, I think.

**Comment by TimSC** [comment]
Closed due to inactivity.
