### ISSUE TITLE
pgmap has mismatched functions

### ISSUE THREAD

**Issue by TimSC** [TimSC/pycrocosm#22]
```
======================================================================
ERROR: test_changeset_auto_close_active (changeset.tests.ChangesetAutoCloseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/pycrocosm/changeset/tests.py", line 1098, in test_changeset_auto_close_active
    cmd.handle([], {})
  File "/var/pycrocosm/changeset/management/commands/closeoldchangesets.py", line 22, in handle
    value = t.CloseChangesetsOlderThan(whereBeforeTimestamp, closedTimestamp,
  File "/usr/local/lib/python2.7/dist-packages/pgmap.py", line 2446, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, PgTransaction, name)
  File "/usr/local/lib/python2.7/dist-packages/pgmap.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'PgTransaction' object has no attribute 'CloseChangesetsOlderThan'

======================================================================
ERROR: test_get_changeset_list (changeset.tests.ChangesetUploadTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/pycrocosm/changeset/tests.py", line 1037, in test_get_changeset_list
    response = anonClient.get(reverse('changeset:list'))
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 536, in get
    **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 340, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 501, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/var/pycrocosm/changeset/views.py", line 692, in list_changesets
    isOpenOnly, isClosedOnly, errStr)
TypeError: GetChangesets() takes exactly 4 arguments (8 given)

----------------------------------------------------------------------
Ran 80 tests in 23.935s

FAILED (errors=2)
```

**Comment by TimSC** [comment]
I think this was a quirk building pgmap. Not sure what is going on! Things seem to have improved since I fixed the swig/cppo5m stuff in pgmap in c78b7c8.
