### ISSUE TITLE
Error 500 when accessing replication data

### ISSUE THREAD

**Issue by TimSC** [TimSC/pycrocosm#42]
Error 500 when accessing https://fosm.org/replication/diff?start=2022-11-7&end=2022-11-8

Python Version: | 3.8.10

Traceback (most recent call last):
  File "/var/pycrocosm/pgmapenv3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/pycrocosm/pgmapenv3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/pycrocosm/./replicate/views.py", line 236, in customdiff
    startTs = startTs.replace(tzinfo=datetime.timezone.utc)

Exception Type: TypeError at /replication/diff
Exception Value: 'tzinfo' is an invalid keyword argument for replace()

**Comment by TimSC** [comment]
Fixed in 526589c
